In [22]:
import numpy as np
import subprocess

In [23]:
# Functions

def oneHot(residue):
    mapping = dict(zip("ACDEFGHIKLMNPQRSTVWY", range(20)))
    if residue in "ACDEFGHIKLMNPQRSTVWY":
        return np.eye(20)[mapping[residue]]
    else:
        return np.zeros(20)
    
    
def reverseOneHot(encoding):
    mapping = dict(zip(range(20),"ACDEFGHIKLMNPQRSTVWY"))
    seq=''
    for i in range(len(encoding)):
        if np.max(encoding[i])>0:
            seq+=mapping[np.argmax(encoding[i])]
    return seq

In [24]:
# Import input file

infilename = "/home/ida/master-thesis/5nmf.fsa"
infile = open(infilename)

infile.readline()
mhc_seq = infile.readline()
infile.readline()
peptide_seq = infile.readline()
infile.readline()
tcrb_seq = infile.readline()
infile.readline()
tcra_seq = infile.readline()

In [31]:
# Model complex with TCRpMHCmodels

path_tcrpmhcmodels = "/home/ida/TCRpMHCmodels/"

path_fasta = "/home/ida/master-thesis/5nmf.fsa"

subprocess.run([path_tcrpmhcmodels + "tcrpmhc_models", "-t", path_fasta])


PermissionError: [Errno 13] Permission denied: '/home/ida/TCRpMHCmodels/tcrpmhc_models'

In [21]:
# Calculate energy Rosetta



In [ ]:
# Calculate energy with FoldX

path_foldx = "/home/ida/foldx/foldx"
path_model_pdb = "/home/ida/foldx/5nmf.pdb"

subprocess.run([path_foldx, "--command=RepairPDB", "--pdb={}".format(path_pdb),
               "--ionStrength=0.05", "--pH=7", "--water=CRYSTAL", "--vdwDesign=2",
                "--out-pdb=1", "--pdbHydrogens=false", "--output-dir=repairPDB_test"])
path_repaired_pdb = "5nmf_Repair.fxout"

subprocess.run([path_foldx, "--command=AnalyseComplex", "--pdb={}".format(path_repaired_pdb), 
                "--output-file=test"])

In [26]:
# Create output

for AA in peptide_seq:
    print(oneHot(AA))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [27]:
import os


In [29]:
os.getcwd()

'/home/ida/master-thesis'